FROM node:12
ENTRYPOINT [ "npx", "nodemon", "./src/server.js" ]
#CMD [ "host" ]
RUN apt-get update && apt-get install -y curl && apt-get install -y jq
WORKDIR /app
COPY package.json /app
RUN npm install
EXPOSE 3000
#COPY src /opt/app_maroto/src
